version: '3.9'

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./volumes/psql:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:$DB_PORT"

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "${REDIS_PASS}" ]
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.13.1-management
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/mnesia
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672"
      - "15692"
