version: '3.9'

x-container: &container
  env_file:
    - .env
  restart: always
  environment:
    PYTHONIOENCODING: "UTF-8"
    LANG: "C.UTF-8"
    LC_ALL: "C.UTF-8"
  logging:
    options:
      max-size: "200k"
      max-file: "10"


services:
  db:
    <<: *container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    sysctls:
      - net.core.somaxconn=2048

  redis:
    <<: *container
    image: redis/redis-stack-server:7.4.0-v3
    environment:
      - REDIS_ARGS=--bind 0.0.0.0 --port 6379 --requirepass ${REDIS_PASS} --maxmemory 1000mb --maxmemory-policy volatile-ttl
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=2048

  rabbitmq:
    <<: *container
    image: rabbitmq:3.13.1-management
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/mnesia
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672"
      - "15692"

  celery:
    <<: *container
    build:
      context: .
    command: celery -A settings worker -l info --prefetch-multiplier=1 -Q default -E

  celerybeat:
    <<: *container
    build:
      context: .
    command: celery -A settings beat -l info

  api:
    <<: *container
    build:
      context: .
    command:
      - gunicorn
      - --certfile=conf/ssl/certificate.crt
      - --keyfile=conf/ssl/certificate.key
      - --config=conf/gunicorn.conf.py
      - --bind=0.0.0.0:443
      - settings.wsgi:application
    ports:
      - "443:443"

  collectstatic:
    <<: *container
    build:
      context: .
    restart: "no"
    command:
      - sh
      - -xec
      - |
        python manage.py migrate
        python manage.py collectstatic --noinput -v 0