version: '3.9'

x-container: &container
  restart: always
  logging:
    options:
      max-size: "200k"
      max-file: "10"
services:
  db:
    <<: *container
    image: postgres:13.3
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./volumes/psql:/var/lib/postgresql/data
    expose:
      - "$DB_PORT"
