# Generated by Django 5.1.6 on 2025-06-01 10:32

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('percent',
                 models.PositiveIntegerField(help_text='Например, 20 для 20%', verbose_name='Скидка в процентах')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец действия')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='PaySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна?')),
                ('is_test', models.BooleanField(db_index=True, default=False, verbose_name='Является тестовой?')),
                ('class_name', models.CharField(db_index=True, max_length=128, unique=True,
                                                verbose_name='Название класса-обработчика')),
                ('ordering', models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='PriceDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Длительность в днях')),
                ('currency', models.CharField(db_index=True, default='RUB', max_length=3, verbose_name='Валюта')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='shop.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices',
                                              to='shop.product')),
            ],
            options={
                'verbose_name': 'Цена/длительность',
                'verbose_name_plural': 'Цены/длительности',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8,
                                               verbose_name='Итоговая сумма для оплаты картой')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buy_descr', models.CharField(max_length=100, verbose_name='Описание покупки')),
                ('token', models.CharField(default=apps.core.utils.generate_md5_token, max_length=64, unique=True,
                                           verbose_name='Внутренний ID')),
                ('price_duration',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases',
                                   to='shop.priceduration', verbose_name='Цена/Длительность продукта')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases',
                                   to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases',
                                           to='bot.userinfo')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code',
                 models.IntegerField(choices=[(-1, 'Возвращён'), (1, 'Создан'), (2, 'Оплачен'), (6, 'Ошибка')],
                                     db_index=True, default=1, verbose_name='Код статуса')),
                ('error_detail', models.JSONField(max_length=2048, null=True, verbose_name='Детали ошибки')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('internal_id', models.CharField(db_index=True, max_length=60, null=True,
                                                 verbose_name='Внутренний ID платежа платежной системы')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                                   to='bot.userinfo')),
                ('pay_system',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments',
                                   to='shop.paysystem', verbose_name='Платежные системы')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                                               to='shop.purchase', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'indexes': [models.Index(fields=['id', 'status_code'], name='shop_paymen_id_ec11b2_idx')],
                'unique_together': {('pay_system_id', 'internal_id')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('expired_date', models.DateTimeField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers',
                                             to='bot.serverconfinfo')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions',
                                   to='bot.userinfo')),
            ],
            options={
                'verbose_name': 'Активная подписка',
                'verbose_name_plural': 'Активные подписки',
                'indexes': [models.Index(fields=['id', 'expired_date'], name='shop_subscr_id_7e79e0_idx')],
            },
        ),
    ]
