# Generated by Django 5.1.6 on 2025-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoForConfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15, null=True)),
                ('publickey', models.CharField(max_length=44)),
                ('privatekey', models.CharField(max_length=44)),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='ServerConfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('end_point', models.CharField(blank=True, max_length=20, null=True)),
                ('publickey', models.CharField(blank=True, max_length=44, null=True)),
                ('privatekey', models.CharField(blank=True, max_length=44, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('is_test', models.BooleanField(default=False, verbose_name='Является тестовой?')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('chat_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('username', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
