# Generated by Django 5.1.6 on 2025-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoForConfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('publickey', models.CharField(max_length=44)),
                ('privatekey', models.CharField(max_length=44)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='ServerConfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, null=True)),
                ('end_point', models.CharField(max_length=20, null=True)),
                ('publickey', models.CharField(max_length=44, null=True)),
                ('privatekey', models.CharField(max_length=44, null=True)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('chat_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('username', models.CharField(max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
