# Generated by Django 5.1.6 on 2025-06-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='infoforconffile',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.serverconfinfo'),
        ),
        migrations.AddField(
            model_name='infoforconffile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userinfo'),
        ),
    ]
