# Generated by Django 4.2.6 on 2023-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoForConfFile',
            fields=[
                ('chat_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('publickey', models.CharField(max_length=44)),
                ('privatekey', models.CharField(max_length=44)),
                ('created_at', models.DateTimeField(default='')),
                ('expires_at', models.DateTimeField(default='')),
                ('enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
