# Generated by Django 5.1.6 on 2025-06-21 16:11

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfinfo',
            name='extra_conf',
            field=models.JSONField(default=apps.core.utils.default_extra_conf),
        ),
    ]
