# Generated by Django 4.2.6 on 2023-11-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_infoforconffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoforconffile',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='infoforconffile',
            name='chat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bot.userinfo'),
        ),
        migrations.AlterField(
            model_name='infoforconffile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='infoforconffile',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
