# Generated by Django 4.2.6 on 2023-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_infoforconffile_start_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoforconffile',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
