# Generated by Django 5.1.6 on 2025-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0003_serverconfinfo_extra_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfinfo',
            name='queue_name',
            field=models.CharField(null=True, unique=True, verbose_name='Название очереди для данного сервера'),
        ),
    ]
