# Generated by Django 4.2.6 on 2023-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_infoforconffile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, null=True)),
                ('server_end_point', models.CharField(max_length=20, null=True)),
                ('server_publickey', models.CharField(max_length=44, null=True)),
                ('server_privatekey', models.CharField(max_length=44, null=True)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
    ]
