# Generated by Django 4.2.6 on 2023-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_serverconfinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverconfinfo',
            old_name='server_end_point',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='serverconfinfo',
            old_name='server_privatekey',
            new_name='privatekey',
        ),
        migrations.RenameField(
            model_name='serverconfinfo',
            old_name='server_publickey',
            new_name='publickey',
        ),
    ]
