# Generated by Django 5.1.6 on 2025-06-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('level', models.IntegerField(
                    choices=[(-1, 'DEBUG'), (0, 'INFO'), (1, 'WARNING'), (2, 'ERROR'), (3, 'CRITICAL')], db_index=True,
                    default=0, verbose_name='Уровень')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs',
                                           to='bot.userinfo')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'indexes': [models.Index(fields=['id', 'date'], name='core_logent_id_874267_idx')],
            },
        ),
    ]
